name: .NET

on:
  push:
    branches: [ "master", "Release/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./BuildVersionManager/nupkg/*.nupkg -k ${GITHUB_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
